version: '3'

services:
  v2ray-tcp:
    image: v2cc/poseidon
    container_name: v2ray-tcp
    restart: always
    ports:
      - "服务端口:服务端口"
    volumes:
      - ./config.json:/etc/v2ray/config.json
